// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC00SdFTkzi79VBjTvfIn-wRvmMRerrhac',
    appId: '1:607370286185:web:7139067f595093fe1efef8',
    messagingSenderId: '607370286185',
    projectId: 'mealsapp-cccf5',
    authDomain: 'mealsapp-cccf5.firebaseapp.com',
    storageBucket: 'mealsapp-cccf5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBCRsf-IV0nn-_TlZS4ggL5J0I8WUXw9M',
    appId: '1:607370286185:android:8b439204c342b3901efef8',
    messagingSenderId: '607370286185',
    projectId: 'mealsapp-cccf5',
    storageBucket: 'mealsapp-cccf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC-2-_-UagSfZ27dTF7lVeez8TcI0KUSY',
    appId: '1:607370286185:ios:154115482a27e6e71efef8',
    messagingSenderId: '607370286185',
    projectId: 'mealsapp-cccf5',
    storageBucket: 'mealsapp-cccf5.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC-2-_-UagSfZ27dTF7lVeez8TcI0KUSY',
    appId: '1:607370286185:ios:154115482a27e6e71efef8',
    messagingSenderId: '607370286185',
    projectId: 'mealsapp-cccf5',
    storageBucket: 'mealsapp-cccf5.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC00SdFTkzi79VBjTvfIn-wRvmMRerrhac',
    appId: '1:607370286185:web:14022bb4d88757b41efef8',
    messagingSenderId: '607370286185',
    projectId: 'mealsapp-cccf5',
    authDomain: 'mealsapp-cccf5.firebaseapp.com',
    storageBucket: 'mealsapp-cccf5.firebasestorage.app',
  );
}
